=== JulienORIOL/projetBDD/schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <!-- On va définir tous nos types ici -->
  <xsd:complexType name="TypeIngredient">
    <xsd:sequence>
      <xsd:element name="nom" type="xsd:string"/>
      <xsd:element name="imageURL" type="xsd:anyURI"/>
      <xsd:element name="quantite" type="xsd:int"/>
      <xsd:element name="unite" type="xsd:string"/>
      <xsd:element name="sante" type="xsd:string"/> <!-- Ce pourrait être le nutriscore de l'ingrédient par exemple -->
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="TypeRecette">
    <xsd:sequence>
      <xsd:element name="titre" type="xsd:string"/>
      <xsd:element name="imageRecetteURL" type="xsd:anyURI"/>
      <xsd:element name="description" type="xsd:string"/>
      <xsd:element name="gastronomie" type="xsd:string"/> <!-- Par exemple végétarien, végan, ou alors Italien, Américain… -->
      <xsd:element name="budget" type="xsd:int"/> <!-- Prix en euros -->
      <xsd:element name="tempsPreparation" type="xsd:int"/>
      <xsd:element name="ingredients" type="TypeIngredient" minOccurs="1" maxOccurs="unbounded"/>   <!-- Au minimum un ingrédient est nécessaire -->
      <xsd:element name="etapes" type="xsd:string" minOccurs="1" maxOccurs="unbounded"/>            <!-- Au minimum une étape est nécessaire -->
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:ID" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="TypeMenu">
    <xsd:sequence>
      <xsd:element name="semaine" type="xsd:int"/>  <!-- Indique sur quel semaine l'entreprise a prévu ce menu -->
      <xsd:element name="recetteRef" type="xsd:IDREFS" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:ID" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="TypeClient">
    <xsd:sequence>
      <xsd:element name="nom" type="xsd:string"/>
      <xsd:element name="adresseLivraison" type="xsd:string"/>
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:ID" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="TypeLivreur">
    <xsd:sequence>
      <xsd:element name="nom" type="xsd:string"/>
      <xsd:element name="entreprise" type="xsd:string"/>
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:ID" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="TypeCommande">
    <xsd:sequence>
      <xsd:element name="clientRef" type="xsd:IDREFS"/>
      <xsd:element name="livreurRef" type="xsd:IDREFS"/>
      <xsd:element name="menuRef" type="xsd:IDREFS"/>
      <xsd:element name="dateCommande" type="xsd:date"/>
      <xsd:element name="status" type="xsd:string"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="TypeCommentaire">
    <xsd:sequence>
      <xsd:element name="auteur" type="xsd:string"/>
      <xsd:element name="date" type="xsd:date"/>
      <xsd:element name="contenu" type="xsd:string"/>
      <xsd:element name="note" type="xsd:int"/>
    </xsd:sequence>
  </xsd:complexType>

  <!-- Cet élément va être notre élément racine -->
  <xsd:element name="boiteRecettes">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="client" type="TypeClient" minOccurs="1" maxOccurs="unbounded"/>
        <xsd:element name="livreur" type="TypeLivreur" minOccurs="1" maxOccurs="unbounded"/>
        <xsd:element name="recette" type="TypeRecette" minOccurs="1" maxOccurs="unbounded"/>
        <xsd:element name="menu" type="TypeMenu" minOccurs="1" maxOccurs="unbounded"/>
        <xsd:element name="commande" type="TypeCommande" minOccurs="1" maxOccurs="unbounded"/>
        <xsd:element name="commentaire" type="TypeCommentaire" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

</xsd:schema>

=== JulienORIOL/projetBDD/recettes.xml
<?xml version="1.0" encoding="UTF-8"?>
<boiteRecettes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">

    <!-- On commence par définir de client qui vont passer commande dans notre entreprise -->
    <client id="client1">
        <nom>Marie Durand</nom>
        <adresseLivraison>12 rue des Lilas, 75015 Paris</adresseLivraison>
    </client>

    <client id="client2">
        <nom>Jean Martin</nom>
        <adresseLivraison>35 avenue du Général Leclerc, 75014 Paris</adresseLivraison>
    </client>

    <client id="client3">
        <nom>Sophie Dupuis</nom>
        <adresseLivraison>78 boulevard de Belleville, 75020 Paris</adresseLivraison>
    </client>

    <!-- On définit des livreurs qui vont pouvoir livrer nos clients qui ont passé commande -->
    <livreur id="livreur1">
        <nom>Thomas Lefebvre</nom>
        <entreprise>ExpressDelivery</entreprise>
    </livreur>

    <livreur id="livreur2">
        <nom>Hugo Dupont</nom>
        <entreprise>Deliveroo</entreprise>
    </livreur>
    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <!-- On définit des recettes qui vont pouvoir être inclues dans nos menus -->
    <recette id="recette_poulet_curry">
        <titre>Poulet au curry</titre>
        <imageRecetteURL>https://static.750g.com/images/1200-675/91ab938d758f762c1f3f84286b121e53/adobestock-307737508.jpeg</imageRecetteURL>
        <description>Poulet tendre dans une sauce curry onctueuse avec du riz !</description>
        <gastronomie>Indienne</gastronomie>
        <budget>25</budget>
        <tempsPreparation>45</tempsPreparation>
        <ingredients>
            <nom>poulet</nom>
            <imageURL>https://cdn02.plentymarkets.com/xlzn8fmweulj/item/images/11268/full/11268-Haehnchen-roh-Lebensmittel-Attrappe-23-cm-11268-Haehnchen-roh-20x16x10cm-641-388-00-1-0-02.png</imageURL>
            <quantite>400</quantite>
            <unite>grammes</unite>
            <sante>B</sante>
        </ingredients>
        <ingredients>
            <nom>pâte de curry</nom>
            <imageURL>https://thegreenquest.org/fr/wp-content/uploads/sites/2/2020/04/Cauliflower-curry-6-of-7-500x500.jpg</imageURL>
            <quantite>3</quantite>
            <unite>cuillères à soupe</unite>
            <sante>C</sante>
        </ingredients>
        <ingredients>
            <nom>crème de coco</nom>
            <imageURL>https://www.jevtobond.com/wp-content/uploads/2016/06/meilleur-lait-creme-coco-cuisine-thai.jpg</imageURL>
            <quantite>200</quantite>
            <unite>millilitres</unite>
            <sante>A</sante>
        </ingredients>
        <ingredients>
            <nom>riz basmati</nom>
            <imageURL>https://www.papillesetpupilles.fr/wp-content/uploads/2016/03/Riz-basmati-©-teleginatania-shutterstock.jpg</imageURL>
            <quantite>300</quantite>
            <unite>grammes</unite>
            <sante>A</sante>
        </ingredients>
        <ingredients>
            <nom>oignon</nom>
            <imageURL>https://media.carrefour.fr/medias/5b35d48684b9300491973d9df3e26314/p_540x540/3000000041185-0.jpg</imageURL>
            <quantite>1</quantite>
            <unite>unité</unite>
            <sante>A</sante>
        </ingredients>
        <ingredients>
            <nom>huile d'olive</nom>
            <imageURL>https://free-dom.fr/wp-content/uploads/2021/01/bienfaits-de-lhuile-dolive-768x512.jpg</imageURL>
            <quantite>2</quantite>
            <unite>cuillères à soupe</unite>
            <sante>A</sante>
        </ingredients>
        <etapes>Chauffer l'huile dans une poêle à feu moyen.</etapes>
        <etapes>Faire revenir le poulet jusqu'à ce qu'il soit doré de tous les côtés.</etapes>
        <etapes>Retirer le poulet et faire revenir les oignons émincés jusqu'à ce qu'ils soient tendres.</etapes>
        <etapes>Ajouter la pâte de curry et laisser cuire pendant une minute.</etapes>
        <etapes>Remettre le poulet dans la poêle, ajouter la crème de coco et porter à ébullition.</etapes>
        <etapes>Réduire le feu et laisser mijoter jusqu'à ce que le poulet soit cuit.</etapes>
        <etapes>Cuire le riz basmati selon les instructions du paquet.</etapes>
        <etapes>Servir le poulet au curry sur un lit de riz basmati.</etapes>
    </recette>

    <recette id="recette_spaghetti_carbonara">
        <titre>Spaghetti Carbonara</titre>
        <imageRecetteURL>https://i.notrefamille.com/1400x787/smart/2020/11/26/52098-large.jpg</imageRecetteURL>
        <description>Spaghetti avec une sauce crémeuse au lard et au fromage !</description>
        <gastronomie>Italienne</gastronomie>
        <budget>20</budget>
        <tempsPreparation>30</tempsPreparation>
        <ingredients>
            <nom>spaghetti</nom>
            <imageURL>https://us.123rf.com/450wm/pioneer111/pioneer1111502/pioneer111150200018/36467938-spaghetti-cru-isolé-sur-fond-blanc.jpg</imageURL>
            <quantite>500</quantite>
            <unite>grammes</unite>
            <sante>B</sante>
        </ingredients>
        <ingredients>
            <nom>lardons</nom>
            <imageURL>https://iod.keplrstatic.com/api/ar_1,c_crop,g_north/c_fill,dpr_auto,f_auto,q_70,w_750/mon_marche/H626_Lardons_natures_BIO_200g.jpg</imageURL>
            <quantite>150</quantite>
            <unite>grammes</unite>
            <sante>D</sante>
        </ingredients>
        <ingredients>
            <nom>œufs</nom>
            <imageURL>https://www.framboizeinthekitchen.com/wp-content/uploads/2018/04/oeufs.jpg</imageURL>
            <quantite>4</quantite>
            <unite>unités</unite>
            <sante>B</sante>
        </ingredients>
        <ingredients>
            <nom>fromage Parmesan râpé</nom>
            <imageURL>https://static1.squarespace.com/static/5c41ee979d5abb9ac95e1230/5dc950ffc850db372781c171/61f3fd21841aae7d5e860592/1643380004181/parmesan_rape-le%2Bfromage.jpg?format=1500w</imageURL>
            <quantite>100</quantite>
            <unite>grammes</unite>
            <sante>C</sante>
        </ingredients>
        <ingredients>
            <nom>gousse d'ail</nom>
            <imageURL>https://mediaorigcdna.qooq.com/cache/201911.1/qooq/images/ingredients/zoom_4.jpg</imageURL>
            <quantite>1</quantite>
            <unite>unité</unite>
            <sante>A</sante>
        </ingredients>
        <etapes>Cuire les spaghetti dans de l'eau salée jusqu'à ce qu'ils soient al dente.</etapes>
        <etapes>Faire revenir les lardons dans une poêle sans ajouter de matière grasse. Ajouter la gousse d'ail écrasée pour plus de saveur.</etapes>
        <etapes>Dans un bol, battre les œufs et ajouter le Parmesan râpé. Assaisonner avec du sel et du poivre noir au goût.</etapes>
        <etapes>Une fois les spaghetti cuits, les égoutter et les remettre dans la casserole. Retirer la poêle du feu et ajouter les spaghetti aux lardons.</etapes>
        <etapes>Verser rapidement le mélange d'œufs et de fromage sur les spaghetti tout en mélangeant énergiquement pour que les œufs ne cuisent pas en omelette.</etapes>
        <etapes>Servir immédiatement, garni de Parmesan supplémentaire et d'un tour de moulin à poivre.</etapes>
    </recette>

    <recette id="recette_salade_césar">
        <titre>Salade César</titre>
        <imageRecetteURL>https://www.adeline-cuisine.fr/wp-content/uploads/2016/07/salade-cesar-recette-sauce-caesar-salad.jpg</imageRecetteURL>
        <description>Salade croquante avec poulet grillé, croûtons et sauce César.</description>
        <gastronomie>Americaine</gastronomie>
        <budget>15</budget>
        <tempsPreparation>25</tempsPreparation>
        <ingredients>
            <nom>laitue romaine</nom>
            <imageURL>https://www.roseedeschamps.fr/wp-content/uploads/2021/05/LAITUE.jpg</imageURL>
            <quantite>1</quantite>
            <unite>unité</unite>
            <sante>A</sante>
        </ingredients>
        <ingredients>
            <nom>blanc de poulet</nom>
            <imageURL>https://resize-gulli.jnsmedia.fr/rcrop/584,326,smartcrop,center-top/img//var/jeunesse/storage/images/gulli/activites/cuisine/plats/blanc-de-poulet-a-la-cannelle/19843314-1-fre-FR/Blanc-de-poulet-a-la-cannelle.jpg</imageURL>
            <quantite>200</quantite>
            <unite>grammes</unite>
            <sante>B</sante>
        </ingredients>
        <ingredients>
            <nom>sauce César</nom>
            <imageURL>https://www.soreal.fr/images/medias/recettes_sauce-caesar-384x3404x.jpg</imageURL>
            <quantite>50</quantite>
            <unite>millilitres</unite>
            <sante>C</sante>
        </ingredients>
        <ingredients>
            <nom>croûtons</nom>
            <imageURL>https://littlesunnykitchen.com/wp-content/uploads/2021/12/Air-Fryer-Croutons-Recipe-1.jpg</imageURL>
            <quantite>50</quantite>
            <unite>grammes</unite>
            <sante>B</sante>
        </ingredients>
        <ingredients>
            <nom>parmesan râpé</nom>
            <imageURL>https://static1.squarespace.com/static/5c41ee979d5abb9ac95e1230/5dc950ffc850db372781c171/61f3fd21841aae7d5e860592/1643380004181/parmesan_rape-le%2Bfromage.jpg?format=1500w</imageURL>
            <quantite>30</quantite>
            <unite>grammes</unite>
            <sante>B</sante>
        </ingredients>
        <ingredients>
            <nom>huile d'olive</nom>
            <imageURL>https://free-dom.fr/wp-content/uploads/2021/01/bienfaits-de-lhuile-dolive-768x512.jpg</imageURL>
            <quantite>2</quantite>
            <unite>cuillères à soupe</unite>
            <sante>A</sante>
        </ingredients>
        <etapes>Laver et hacher la laitue romaine, puis la placer dans un grand saladier.</etapes>
